src/Entity/MarquePage.php
<?php

namespace App\Entity;

use App\Repository\MarquePageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as assert;

#[ORM\Entity(repositoryClass: MarquePageRepository::class)]
class MarquePage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commentaire = null;


    #[ORM\ManyToMany(targetEntity: MotsCles::class, mappedBy: 'lien')]
    //#[assert\Type(type:"App\Entity\MotsCles")]
    #[assert\Valid]
    private Collection $motsCles;

    public function __construct()
    {
        $this->motsCles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

   

    public function addMotsCle(MotsCles $motsCle): static
    {
        if (!$this->motsCles->contains($motsCle)) {
            $this->motsCles->add($motsCle);
            $motsCle->addLien($this);
        }

        return $this;
    }

    public function removeMotsCle(MotsCles $motsCle): static
    {
        if ($this->motsCles->removeElement($motsCle)) {
            $motsCle->removeLien($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, MotsCles>
     */
    public function getMotsCles(): Collection
    {
        return $this->motsCles;
    }

    public function __toString(): string
    {
        $res =  $this->url ." - ";
        foreach ($this->getMotsCles() as $mc) {
            $res .= $mc ." ";
        }

        return $res;
    }
}

src/Form/Type/MarquePageType.php
<?php
namespace App\Form\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\MarquePage;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\MotsCles;

class MarquePageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('url', TextType::class)
        ->add('date_creation', DateType::class)
        ->add('commentaire', TextType::class)
        ->add('mots_cles', EntityType::class, [
            'class' => MotsCles::class,
            'choice_label' => 'mots_cles',
            'multiple' => true,
            'expanded' => true,
        ])
        ->add('valider', SubmitType::class);
    }
    // Ici, on défini de manière explicite le « data_class »
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MarquePage::class,
        ]);
    }
    
    
}

src/Controller/MarquePageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\MarquePage;
use App\Entity\MotsCles;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Form\Type\MarquePageType;


#[Route("/marque/page", requirements: ["_locale" => "en|es|fr"], name: "marque_page_")]
class MarquePageController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $marques_pages = $entityManager->getRepository(MarquePage::class)->findAll();


        return $this->render('marque_page/index.html.twig', [
            'controller_name' => 'MarquePageController',
            'marques_pages' => $marques_pages,
        ]);
    }

    // #[Route("/ajouter", name: "ajouter")]
    // public function ajouterMarquePage(EntityManagerInterface $entityManager): Response
    // {
    //     $mots_cles = new MotsCles();
    //     $mots_cles->setMotsCles("framework");

    //     $mots_cles2 = new MotsCles();
    //     $mots_cles2->setMotsCles("php");
        
    //     $marques_pages = new MarquePage();
    //     $marques_pages->setUrl("https://www.symfony.com/");
    //     $marques_pages->setDateCreation(new \DateTime());
    //     $marques_pages->setCommentaire("C'est un framework PHP très puissant et très pratique");
    //     $marques_pages->addMotsCle($mots_cles);
    //     $marques_pages->addMotsCle($mots_cles2);


    //     $entityManager->persist($mots_cles);
    //     $entityManager->persist($mots_cles2);
    //     $entityManager->persist($marques_pages);
    //     $entityManager->flush();

    //     return new Response("MarquePage sauvegardé avec l'id ". $marques_pages->getId());
    // }

    #[Route("/detail/{id<\d+>}", name: "detail")]
    public function afficherMarquePage(int $id, EntityManagerInterface $entityManager):Response
    {
        $marque_page = $entityManager->getRepository(MarquePage::class)->find($id);
        if (!$marque_page) {
            throw $this->createNotFoundException(
            "Aucun marque-page avec l'id ". $id
            );
        }
        return $this->render('marque_page/detail.html.twig', [
            'marque_page' => $marque_page,
        ]);
    }

    #[Route("/success", name:"success")]
    public function succes(EntityManagerInterface $entityManager)
    {
        return $this->render('marque_page/ajout_succes.html.twig');
    }
    
    #[Route("/ajout", name:"ajout")]
    public function ajoutMarquePage(Request $request, entityManagerInterface $entityManager)
    {
        // Création d’un objet Livre vierge
        $marque_page = new MarquePage();
        $form = $this->createForm(MarquePageType::class, $marque_page);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() : pour récupérer les données
            // Les données sont déjà stockées dans la variable d’origine
            // $marque_page = $form->getData();
            // ... Effectuer le/les traitements(s) à réaliser
            // Par exemple :
            $entityManager->persist($marque_page);
            $entityManager->flush();
            return $this->redirectToRoute('marque_page_success');
        }
        return $this->render('marque_page/ajout.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route("/modifier/{id<\d+>}", name:"modifier")]
    public function modifierMarquePage(int $id, Request $request, entityManagerInterface $entityManager)
    {
        $marque_page = $entityManager->getRepository(MarquePage::class)->find($id);
        
        if (!$marque_page) {
            throw $this->createNotFoundException(
            "Aucun livre avec l'id ". $id
            );
        }
        
        $form = $this->createForm(MarquePageType::class, $marque_page);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //die($marque_page);
            $entityManager->persist($marque_page);
            /*
            foreach ($marque_page->getMotsCles() as $mots_cles) {
                //$mots_cles->addLien($marque_page);
                $entityManager->persist($mots_cles);
            }
            */
            $entityManager->flush();
            return $this->redirectToRoute('marque_page_success');
        }
        
        return $this->render('marque_page/ajout.html.twig', [
            'form' => $form,
        ]);
    }
    
}

templates/marque_page/ajout.html.twig
{% extends 'marque_page/layout.html.twig' %}

{% block content_detail %}
    <a class="link" href="{{ path('marque_page_index') }}">⬅️Retour arrière</a>
    {{form(form)}}
{% endblock %}

templates/marque_page/ajout_succes.html.twig
{% extends 'marque_page/layout.html.twig' %}

{% block content_detail %}
    <h2>Marque-page ajouter avec succès</h2>
    <a class="link" href="{{ path('marque_page_index') }}">⬅️Retour à la liste</a>
{% endblock %}

templates/marque_page/detail.html.twig
{% extends 'marque_page/layout.html.twig' %}

{% block content_detail %}
    <h2>Detail du Marque page avec l'id : {{marque_page.id}}</h2>
    <a class="link" href="{{ path('marque_page_index') }}">⬅️Retour arrière</a>
    <table>
        <thead>
            <tr>
                <th scope="col">Libellé</th>
                <th scope="col">Valeur</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>ID</td>
                <td>{{marque_page.id}}</td>
            </tr>
            <tr>
                <td>URL</td>
                <td>{{marque_page.url}}</td>
            </tr>                 
            <tr>
                <td>Date de création</td>
                <td>{{marque_page.dateCreation|date("d/m/Y")}}</td>
            </tr>
            <tr>
                <td>Commentaire</td>
                <td>{{marque_page.commentaire}}</td>
            </tr>
            <tr>
                <td>Mots-clés</td>
                <td>
                    {% for mc in marque_page.motsCles %}
                        <p class="motcle">{{mc.motsCles}}</p>
                    {% endfor %}
                </td>
            </tr>
      </tbody>
    </table>
{% endblock %}

templates/marque_page/index.html.twig
{% extends 'marque_page/layout.html.twig' %}

{% block content_detail %}    
    <h2>Liste complète des marques-pages</h2>
    <a class="link" href="{{ path('marque_page_ajout') }}">Ajouter un marque-page</a>
    <table>
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">URL</th>
                <th scope="col">Date</th>
                <th scope="col">Commentaire</th>
                <th scope="col">Mots-clés</th>
                <th scope="col">Modifier</th>
            </tr>
        </thead>
        <tbody>
            {% for page in marques_pages %}
                <tr>
                    <td>{{page.id}}</td>
                    <td><a class="link" href="{{ path('marque_page_detail', { 'id': page.id }) }}">{{page.url}}</a></td>
                    <td>{{page.dateCreation|date("d/m/Y")}}</td>
                    <td>{{page.commentaire}}</td>
                    <td>
                        {% for mc in page.motsCles %}
                            {{mc.motsCles}}
                        {% endfor %}
                    </td>
                    <td><a class="link" href="{{ path('marque_page_modifier', { 'id': page.id }) }}">Modifier</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/marque_page/layout.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link href="{{asset("css/marque_page.css")}}" rel="stylesheet"/>
{% endblock %}
{% block title %}Marque Page{% endblock %}
{% block content %}
<h1>Marque Page</h1>
<p>Ici vous trouverez un tableau de marque pages (lien pas ceux pour les livres)</p>
{% block content_detail %}{% endblock %}
{% endblock %}