src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Rue = null;

    #[ORM\Column(length: 255)]
    private ?string $Ville = null;

    #[ORM\Column(length: 255)]
    private ?string $Pays = null;

    #[ORM\Column]
    private ?int $CodePostal = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRue(): ?string
    {
        return $this->Rue;
    }

    public function setRue(string $Rue): static
    {
        $this->Rue = $Rue;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): static
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): static
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): static
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }
}

src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[Assert\Type(type:"App\Entity\Adresse")]
    #[Assert\Valid]
    private ?Adresse $adresse = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }
}

src/Form/Type/EmployeType.php
<?php
namespace App\Form\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Employe;
use App\Form\Type\AdresseType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('nom', TextType::class)
        ->add('prenom', TextType::class)
        ->add('adresse', AdresseType::class)
        ->add('valider', SubmitType::class);
    }
    // Ici, on défini de manière explicite le « data_class »
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
    
    
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Employe;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\Type\EmployeType;
use App\Form\Type\AdresseType;


#[Route("/employe", requirements: ["_locale" => "en|es|fr"], name: "employe_")]
class EmployeController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $employes = $entityManager->getRepository(Employe::class)->findAll();

        return $this->render('employe/index.html.twig', [
            'controller_name' => 'EmployeController',
            'employes' => $employes,
        ]);
    }

    #[Route("/detail/{id<\d+>}", name: "detail")]
    public function afficherEmploye(int $id, EntityManagerInterface $entityManager):Response
    {
        $employe = $entityManager->getRepository(Employe::class)->find($id);
        if (!$employe) {
            throw $this->createNotFoundException(
            "Aucun employé avec l'id ". $id
            );
        }
        return $this->render('employe/detail.html.twig', [
            'employe' => $employe,
        ]);
    }

    #[Route("/success", name:"succes")]
    public function succes(EntityManagerInterface $entityManager)
    {
        return $this->render('employe/ajout_succes.html.twig');
    }

    #[Route("/ajout", name:"ajout")]
    public function ajoutEmploye(Request $request, entityManagerInterface $entityManager)
    {
        // Création d’un objet employe vierge
        $employe = new Employe();
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() : pour récupérer les données
            // Les données sont déjà stockées dans la variable d’origine
            // $employe = $form->getData();
            // ... Effectuer le/les traitements(s) à réaliser
            // Par exemple :
            $entityManager->persist($employe);
            $entityManager->flush();
            return $this->redirectToRoute('employe_succes');
        }
        return $this->render('employe/ajout.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route("/modifier/{id<\d+>}", name:"modifier")]
    public function modifierEmploye(int $id, Request $request, entityManagerInterface $entityManager)
    {
        $employe = $entityManager->getRepository(Employe::class)->find($id);
        
        if (!$employe) {
            throw $this->createNotFoundException(
            "Aucun employé avec l'id ". $id
            );
        }
        
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($employe);
            $entityManager->flush();
            return $this->redirectToRoute('employe_succes');
        }
        
        return $this->render('employe/ajout.html.twig', [
            'form' => $form,
        ]);
    }
}

templates/employe/ajout.html.twig
{% extends 'employe/layout.html.twig' %}

{% block content_detail %}
    <a class="link" href="{{ path('employe_index') }}">⬅️Retour arrière</a>
    {{ form(form) }}
{% endblock %}

templates/employe/ajout_succes.html.twig
{% extends 'employe/layout.html.twig' %}

{% block content_detail %}
    <h2>Employé ajouter avec succès</h2>
    <a class="link" href="{{ path('employe_index') }}">⬅️Retour à la liste</a>
{% endblock %}

templates/employe/detail.html.twig
{% extends 'employe/layout.html.twig' %}

{% block content_detail %}
    <h2>Detail de l'employé avec l'id : {{employe.id}}</h2>
    <a class="link" href="{{ path('employe_index') }}">⬅️Retour arrière</a>
    <table>
        <thead>
            <tr>
                <th scope="col">Libellé</th>
                <th scope="col">Valeur</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>ID</td>
                <td>{{employe.id}}</td>
            </tr>
            <tr>
                <td>Prénom</td>
                <td>{{employe.prenom}}</td>
            </tr>                 
            <tr>
                <td>Nom</td>
                <td>{{employe.nom}}</td>
            </tr>
            <tr>
                <td>Rue</td>
                <td>{{employe.adresse.rue}}</td>
            </tr>
            <tr>
                <td>Ville</td>
                <td>
                    {{employe.adresse.ville}}
                </td>
            </tr>
            <tr>
                <td>Pays</td>
                <td>
                    {{employe.adresse.pays}}
                </td>
            </tr>
            <tr>
                <td>Code Postal</td>
                <td>
                    {{employe.adresse.codePostal}}
                </td>
            </tr>
      </tbody>
    </table>
{% endblock %}

templates/employe/index.html.twig
{% extends 'employe/layout.html.twig' %}

{% block content_detail %}
    <h2>Liste complète des Employés</h2>
    <a class="link" href="{{ path('employe_ajout') }}">Ajouter un employé</a>
    <table>
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Adresse</th>
                <th scope="col">Modifier</th>
            </tr>
        </thead>
        <tbody>
            {% for employe in employes %}
                <tr>
                    <td>{{employe.id}}</td>
                    <td><a class="link" href="{{ path('employe_detail', { 'id': employe.id }) }}">{{employe.prenom}} </a></td>
                    <td><a class="link" href="{{ path('employe_detail', { 'id': employe.id }) }}">{{employe.nom}}</a></td>
                    {% if employe.adresse %}
                    <td>
                        {{employe.adresse.rue}}, {{employe.adresse.ville}}, {{employe.adresse.pays}}, {{employe.adresse.codePostal}}
                    </td>
                    {% endif %}
                    <td><a class="link" href="{{ path('employe_modifier', { 'id': employe.id }) }}">Modifier</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/employe/layout.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link href="{{asset("css/livre.css")}}" rel="stylesheet"/>
{% endblock %}
{% block title %}Employés{% endblock %}
{% block content %}
<h1>Employés</h1>
<p>Ici vous trouverez un tableau des employés d'une entreprise fictive (elle existe pas et a pour PNJ un gars sorti de nulle part qui s'incruste en plein cours...).</p>
{% block content_detail %}{% endblock %}

{% endblock %}